name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: JGean09
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg

      - name: Upload Snake GIF and SVG
        uses: actions/upload-artifact@v3
        with:
          name: snake-files
          path: dist/github-snake.gif, dist/github-snake.svg
